// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  quote: dynamic(() => import("./Quote")),
  text_block: dynamic(() => import("./TextBlock")),
};
